par_1:
  vals: [ 1.0e-3, 5.0e-4, 1.0e-4 ]
  name: ALPHA
  section: config_disk

par_2:
  vals: [NoAccretion]
  name: model
  section: config_planet

par_3:
  vals: [3.5]
  section: config_planet
  name: t_0

double_disks: True
save_disk: True
output_name: only_disk
