# config file for Mah et al. (2023)
# M_star = 0.3 M_Sun, used together with jobs/mstar03_C60.yaml
# to generate a part of Fig. 1

# Take care of units here! Otherwise adapt in import_config.scale_units!
# Physical parameters
config_disk:
  model:                        DiskLabDisk
  M_STAR:                       0.3        # mass of central star in sun massses
  ALPHA:                        5.0e-4     # Alpha viscosity
  ALPHAHEIGHT:                  1.0e-4
  M0:                           0.03       # needed for DiskLabDisk
  R0:                           110         # needed for DiskLabDisk
  DTG_total:                    0.0142        # Dust to gas ratios
  static:                       False
  evaporation:                  True        
  static_stokes:                False
  tau_disk:                     1.0e4
  begin_photoevap:              10.0  # Myr
  temp_evol:                    False
  evap_width:                   1.0e-3
  lstar:                        0.332

chemistry:
  FeH: 0.0
  use_FeH: False   # use FeH proxy fit according to Bitsch & Battistini (2020)
  C_frac: 0.6      # Fraction of C/H in C (will be reduced from CH4)
  CO_frac: 0.2
  CH4_frac: 0.1
  CO2_frac: 0.1

config_planet:
  model: NoAccretion
  matter_removal: True
  use_heat_torque: True
  use_dynamical_torque: True
  migration: False
  M0_fact: 1
  a_p: 5.0
  t_0: 10.5       # time before planets start growing, total time: time_disk_0+t_0
  rho_c: 5.5      # density of the core (g/cm**3)
  r_in: 0.2       
  keep_peb_iso: True
  use_pebiso_diffusion: False

config_pebble_accretion:
  u_frag:                       5.0      # m/s
  epsilon_p: 0.5

config_gas_accretion:
  kappa_env:                    0.05
  f_machida:                    1
  f_disk_max:                   1.0

# modelling parameters
defaults:
  DEF_R_IN:                     0.1      # inner r boundary (in AU) 
  DEF_R_OUT:                    1000     # outer r boundary (in AU)
  DEF_GRIDSIZE:                 500      # radial gridsize
  DEF_LIN_SPACING:              False    # Spacing of radial grid
  DEF_TIMESTEP:                 10      # Timestep in years

output:
  name:                        solar_mstar03_C60
  save_disk:                   True
  save_interval:               5000  # time in years
  save_disk_interval:          10
